package main

import (
	"fmt"
	"log"
	"os"
	"strings"
	"text/template"

	"github.com/oceanscan/imc-go"
)

var typeMap = map[string]string{
	"int8_t":       "int8",
	"uint8_t":      "uint8",
	"int16_t":      "int16",
	"uint16_t":     "uint16",
	"int32_t":      "int32",
	"uint32_t":     "uint32",
	"int64_t":      "int64",
	"fp32_t":       "float32",
	"fp64_t":       "float64",
	"plaintext":    "string",
	"rawdata":      "[]byte",
	"message":      "*Message",
	"message-list": "[]*Message",
}

var tmpl = `// Code generated by gen_messages. DO NOT EDIT.
package imc

import (
	"fmt"
)

{{range .Messages}}
// {{.Abbrev}} message
type {{.Abbrev}} struct {
	Header Header
{{range .Fields}}	{{goName .Abbrev}} {{goType .Type}}
{{end}}	Extra map[string]any
}

func (m *{{.Abbrev}}) GetHeader() *Header { return &m.Header }
func (m *{{.Abbrev}}) GetMGID() uint16 { return {{.ID}} }

func (m *{{.Abbrev}}) ToMessage() *Message {
	res := &Message{
		Header: m.Header,
		Fields: make(map[string]any),
	}
	res.Header.MGID = {{.ID}}
{{range .Fields}}	res.Fields["{{.Abbrev}}"] = m.{{goName .Abbrev}}
{{end}}	for k, v := range m.Extra {
		res.Fields[k] = v
	}
	return res
}

func (m *{{.Abbrev}}) FromMessage(msg *Message) error {
	if msg.Header.MGID != {{.ID}} {
		return fmt.Errorf("invalid MGID: expected {{.ID}}, got %d", msg.Header.MGID)
	}
	m.Header = msg.Header
{{range .Fields}}	if val, ok := msg.Fields["{{.Abbrev}}"]; ok {
		m.{{goName .Abbrev}} = {{goHelper .Type}}(val)
	}
{{end}}	m.Extra = make(map[string]any)
	for k, v := range msg.Fields {
		switch k {
		{{range .Fields}}case "{{.Abbrev}}":
			continue
		{{end}}default:
			m.Extra[k] = v
		}
	}
	return nil
}
{{end}}

func (p *Protocol) CreateTyped(abbrev string, msg *Message) (IMessage, error) {
	switch abbrev {
{{range .Messages}}	case "{{.Abbrev}}":
		m := &{{.Abbrev}}{}
		if msg != nil {
			err := m.FromMessage(msg)
			return m, err
		}
		return m, nil
{{end}}	default:
		return nil, fmt.Errorf("unknown typed message: %s", abbrev)
	}
}
`

func goName(abbrev string) string {
	parts := strings.Split(abbrev, "_")
	for i := range parts {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}

func goType(imcType string) string {
	if t, ok := typeMap[imcType]; ok {
		return t
	}
	return "any"
}

func goHelper(imcType string) string {
	switch imcType {
	case "int8_t":
		return "ToInt8"
	case "uint8_t":
		return "ToUint8"
	case "int16_t":
		return "ToInt16"
	case "uint16_t":
		return "ToUint16"
	case "int32_t":
		return "ToInt32"
	case "uint32_t":
		return "ToUint32"
	case "int64_t":
		return "ToInt64"
	case "fp32_t":
		return "ToFloat32"
	case "fp64_t":
		return "ToFloat64"
	case "plaintext":
		return "ToString"
	case "rawdata":
		return "ToByteSlice"
	case "message":
		return "ToGenericMessage"
	case "message-list":
		return "ToGenericMessageList"
	}
	return "val"
}

func goExportType(imcType string) string {
	t := goType(imcType)
	t = strings.ReplaceAll(t, "[]", "")
	t = strings.ReplaceAll(t, "*", "")
	return strings.ToUpper(t[:1]) + t[1:]
}

func main() {
	proto, err := imc.ParseXML("IMC.xml")
	if err != nil {
		log.Fatal(err)
	}

	f, err := os.Create("messages.go")
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	t := template.Must(template.New("messages").Funcs(template.FuncMap{
		"goName":       goName,
		"goType":       goType,
		"goHelper":     goHelper,
		"goExportType": goExportType,
	}).Parse(tmpl))

	err = t.Execute(f, proto)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println("Successfully generated messages.go")
}
